const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt1",
      category: "Shierts",
      image: "/images/p1.jpg",
      price: 120,
      CountInStock: 10,
      Brand: "Nike",
      rating: 4.5,
      nameReviews: 10,
      description: "Hght quality shirt",
    },
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt2",
      category: "Shierts",
      image: "/images/p2.jpg",
      price: 120,
      CountInStock: 10,
      Brand: "Nike",
      rating: 4.5,
      nameReviews: 10,
      description: "Hght quality shirt",
    },
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt3",
      category: "Shierts",
      image: "/images/p3.jpg",
      price: 120,
      CountInStock: 10,
      Brand: "Nike",
      rating: 4.5,
      nameReviews: 10,
      description: "Hght quality shirt",
    },
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt4",
      category: "Shierts",
      image: "/images/p4.jpg",
      price: 120,
      CountInStock: 10,
      Brand: "Nike",
      rating: 4.5,
      nameReviews: 10,
      description: "Hght quality shirt",
    },
  ],
};
export default data;
